### ISSUE TITLE
Debian 10 clang 8 : failed to install clang

### ISSUE THREAD

**Issue by BertrandDekoninck** [plaurent/gnustep-build#22]
First run of GNUstep-20-buildon-debian10.sh on a fresh buster  system. Install failed because apt.llvm.org pubkey isn't installed.
One need to run first the following command
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
# Fingerprint: 6084 F3CF 814B 57C1 CF12 EFD5 15CF 4D18 AF4F 7421

**Comment by plaurent** [comment]
@BertrandDekoninck That is odd. I have just tried that build script under Docker starting with a brand new Debian image (`FROM debian:buster`) and it builds fine.

Are you certain that is what fixed your issue?

I don't believe adding your command will cause any issues with the build, so I'm not opposed to adding it in if it really helps in some cases.

**Comment by BertrandDekoninck** [comment]
I can confirm that install went fine after installing the key with this command I've taken from https://apt.llvm.org. You can see on the installation instructions on this page that this is the first installation step.

**Comment by BertrandDekoninck** [comment]
I've done buster install using this iso with non-free firmware packages : http://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/10.7.0-live+nonfree/amd64/iso-hybrid/debian-live-10.7.0-amd64-standard+nonfree.iso
